name: Autograding Tests
'on': [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student code
        uses: actions/checkout@v4
      
      - name: Download teacher's test repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT_TOKEN }}
        run: |
          git clone https://${{ secrets.ORG_PAT_TOKEN }}@github.com/IcensRAGHomework/assignment-tests-.git temp-tests
          
      - name: Cache Python dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install --cache-dir ~/.cache/pip -r requirements.txt
        
      - name: Prepare tests
        run: |
          cp temp-tests/test_assignment.py .
    
      - name: Run tests and check for pass/fail
        id: test_step
        run: |
          if pytest test_assignment.py::test_add; then
            echo "SCORE=30" >> $GITHUB_ENV
            echo '{"name": "pytest", "score": 30}' >> test_results.json
          else
            echo "SCORE=0" >> $GITHUB_ENV
            echo '{"name": "pytest", "score": 0}' >> test_results.json
          fi

      - name: Display score
        run: echo "Final Score:${{ env.SCORE }}"

      - name: Report grade to GitHub Classroom
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          token: ${{ secrets.ORG_PAT_TOKEN }}
          runners: |
            [
              {
                "name": "Test Suite",
                "result": "${{ env.SCORE }}"
              }
            ]
